### ISSUE TITLE
Consider also looking at native name when GetCountryByName

### ISSUE THREAD

**Issue by CasperCBroeren** [nager/Nager.Country#10]
I noticed that while using GetCountryByName the native name is not searched. Is this intentional? 
I would really like to have this searched because it gives me more possibilities to clean manual user input. 
Thanks for the great package and I hope this might be in a next version

**Comment by tinohager** [comment]
hi, have you try this https://github.com/nager/Nager.Country#get-the-name-of-the-country-in-the-requested-language-nuget---nagercountrytranslation

**Comment by CasperCBroeren** [comment]
Thanks, it inspired me to solve my problem.
