### ISSUE TITLE
Include Emoji flags

### ISSUE THREAD

**Issue by MarcosCostaDev** [nager/Nager.Country#11]
What you think add emoji code in the country information based on [Emojipedia](https://emojipedia.org/flags/)?

**Comment by tinohager** [comment]
if this work for the problem?
https://stackoverflow.com/questions/47272182/how-to-convert-two-letter-country-codes-to-flag-emojis/47272445

**Comment by MarcosCostaDev** [comment]
Yes, it worked. I had found this yesterday. Thank you

**Comment by tinohager** [comment]
so I would close this issue, I think the above solution makes more sense
