### ISSUE TITLE
Please add country code information for `AN` https://en.wikipedia.org/wiki/Netherlands_Antilles

### ISSUE THREAD

**Issue by AchoArnold** [nager/Nager.Country#13]
Please add country code information for `AN` https://en.wikipedia.org/wiki/Netherlands_Antilles

**Comment by amirvenus** [comment]
Kosovo and Accession are also some of the missing ones.

**Comment by tinohager** [comment]
@amirvenus https://github.com/nager/Nager.Country/issues/14

**Comment by tinohager** [comment]
What is the current status of the country it was dissolved in 2010?
