### ISSUE TITLE
Please add country code information for XK

### ISSUE THREAD

**Issue by AlexKulbako** [nager/Nager.Country#14]
Your library cannot be used for production purposes as it does not support all country codes ...

**Comment by tinohager** [comment]
What countries are all missing from your point of view?

**Comment by tinohager** [comment]
https://en.wikipedia.org/wiki/International_recognition_of_Kosovo

I think as long as there is no clear recognition of this, it will remain as it is.

**Comment by AlexKulbako** [comment]
Thank you for the answer. Agree with that. It is also not available in iso3166.

**Comment by amirvenus** [comment]
> https://en.wikipedia.org/wiki/International_recognition_of_Kosovo
> 
> I think as long as there is no clear recognition of this, it will remain as it is.

I think it would be great to have it added as I would love to use this for production and some of my clients are [oddly] based in Kosovo. 

Also, on the missing note, there are some phone calling codes missing which I have extracted myself based on a research (so that all UTs can pass):

                                 ```
                                 "AQ" => "672",
			        "BV" => "55",
			        "TF" => "262",
			        "HM" => "0",
			        "UM" => "246",
```

**Comment by SentinelBorg** [comment]
I also wished Kosovo (XK/XKX) would be added. I get that code from SAP and other systems in Swiss hospitals all the time.

**Comment by tinohager** [comment]
> https://en.wikipedia.org/wiki/International_recognition_of_Kosovo
> 
> I think as long as there is no clear recognition of this, it will remain as it is.

**Comment by SentinelBorg** [comment]
> > https://en.wikipedia.org/wiki/International_recognition_of_Kosovo
> > I think as long as there is no clear recognition of this, it will remain as it is.

But it is recognized in most Western Countries and because of all the migrants from that area also widely used in for example Switzerland, Germany and probably also Austria.
Maybe mark it as "temporary/unofficial" and extent the two Get() methods with an optional parameter/flags to also consider those if the users wishes so.

**Comment by tinohager** [comment]
Nager.Country base on Iso3166

Kosovo is disputed under international law. 115 of the 193 UN members have recognized Kosovo to date. "X" codes such as perhaps "XK" or "XXK," etc., are private, non-authoritative assignments. ISO codes do not exist to date.

**Comment by wstaelens** [comment]
XK is in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2 

> ISO 3166-1 alpha-2 [codes](https://en.wikipedia.org/wiki/Code) are two-letter [country codes](https://en.wikipedia.org/wiki/Country_code) **defined in [ISO 3166-1](https://en.wikipedia.org/wiki/ISO_3166-1), part of the [ISO 3166](https://en.wikipedia.org/wiki/ISO_3166) [standard](https://en.wikipedia.org/wiki/Standardization)[[1]]**(https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#cite_note-iso3166-info-1) published by the [International Organization for Standardization](https://en.wikipedia.org/wiki/International_Organization_for_Standardization) (ISO), to represent [countries](https://en.wikipedia.org/wiki/Country), [dependent territories](https://en.wikipedia.org/wiki/Dependent_territory), and special areas of geographical interest.

> The code XK is being used by the [European Commission](https://en.wikipedia.org/wiki/European_Commission)[[28]](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#cite_note-28) the [IMF](https://en.wikipedia.org/wiki/International_Monetary_Fund), and [SWIFT](https://en.wikipedia.org/wiki/Society_for_Worldwide_Interbank_Financial_Telecommunication),[[29]](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#cite_note-29) the [CLDR](https://en.wikipedia.org/wiki/Common_Locale_Data_Repository), and other organizations as a temporary country code for [Kosovo](https://en.wikipedia.org/wiki/Kosovo).[[30]](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#cite_note-30)

Looks like it is part of ISO 3166.... as ISO 3166-1_alpha-2 is part of ISO 3166.

**Comment by g01198628y** [comment]
XK is in ISO 3166, why not add this ? thanks.

**Comment by romaromaniv** [comment]
Hi @tinohager 

Let me add one more vote for having Kosovo country in the library.

The product my team developing is supposed to be launched in many European countries especially with EUR currency.

Also finding good idea https://github.com/nager/Nager.Country/issues/14#issuecomment-1590876418
potentially to have separate list like PartiallyRecognizedList etc

Also we using Nokia HERE services like https://revgeocode.search.hereapi.com/v1/revgeocode
And it easily parsing Kosovo latitude/longitude returning 3 letters code "KOS" 

Thanks!

Regards, Roman

**Comment by tinohager** [comment]
New version has been released
