### ISSUE TITLE
Please, edit SubRegion to SubRegion.EasternEurope for Croatia

### ISSUE THREAD

**Issue by KirillUsckov** [nager/Nager.Country#15]
https://github.com/nager/Nager.Country/tree/master/src/Nager.Country/CountryInfos/CroatiaCountryInfo.cs 
Please, change SubRegion to SubRegion.EasternEurope for Croatia.

**Comment by tinohager** [comment]
Okay mledoze have also changes the subregions 

https://github.com/mledoze/countries/commit/a04e0d64474443d980048ff5a06bb9b447b60042
