### ISSUE TITLE
Adding non-standard currency codes that are not part of ISO 4217

### ISSUE THREAD

**Issue by HenrikBagger** [nager/Nager.Country#18]
Greetings,
We use Nager.Country for our currency code validation. However we've lately run into assets on the market with currency codes that are not a part of the ISO 4217 standard such as CNH which is the offshore equivalent of CNY.
I was hoping that we could add the following non-standard currency codes into Nager.Country in some way:
https://en.wikipedia.org/wiki/ISO_4217#Non-standard_codes

**Comment by tinohager** [comment]
It would be necessary to create them additionally and to introduce a type of what is an official and an unofficial currency.
That would already mean a few hours of work

**Comment by HenrikBagger** [comment]
That is fair. We'll look into another way of allowing these problematic currency codes. Thank you for taking your time to hear me out.
