### ISSUE TITLE
NullReferenceException on unknown country code

### ISSUE THREAD

**Issue by JonAnders** [nager/Nager.Country#19]
When an unknown country code is passed to `GetCountryTranslatedName(...)`, a `NullReferenceException` is thrown. It would be helpful if a more specific exception detailing the error was used.

My suggestion would be an `ArgumentException` with a message specifying that the `alpha2or3Code` parameter contains an unknown country code.

Example code:
```c#
new TranslationProvider().GetCountryTranslatedName("ZZ", CultureInfo.CurrentUICulture);
```

**Comment by JonAnders** [comment]
Awesome! I see the PR is already merged, but it looks good to me!

Thank you!

**Comment by JonAnders** [comment]
I just realized that this might be a breaking change though.

If someone are using something like `new CountryProvider().GetCountry(countryCode) != null` to check if a country code is valid, that would no longer work.

I think the semantic difference between "get the translated name for this country" vs "get this country" might justify throwing exception in the first case and returning null in the second, but I'm not sure. What do you think?

Also, since `GetCountryTranslatedName` is already throwing an exception, a more specific exception is less likely to break anything.

**Comment by tinohager** [comment]
Yes we would have to increase the `MAJOR` version here now we can add another method that returns a true/false with `Try`

`bool TryGetCountry(string countryCode, out ICountryInfo countryInfo)`
