### ISSUE TITLE
Language names of a country in all different cultures

### ISSUE THREAD

**Issue by sthewissen** [nager/Nager.Country#2]
Currently, the name of all countries is in here translated to all the different cultures. Are there plans for the future to do something similar for the language of those countries? E.g:

```
"languages": [
    {
      "languageCode": "EN",
      "name": "Dutch"
    },
    {
      "languageCode": "NL",
      "name": "Nederlands"
    },
    {
      "languageCode": "FR",
      "name": "Néerlandais"
    },
    ...
  ],
```

This package offers something similar, but is not open source and not maintained:
https://www.nuget.org/packages/IsoNames.NETStandard/

It's also missing a few things from what I can see in my applications.

**Comment by tinohager** [comment]
Can you describe an example of what exactly you want?

**Comment by tinohager** [comment]
Okay I now understand your request. Currently it is not planned but you are welcome to send a pull request with the extension.

**Comment by sthewissen** [comment]
I could look into it, but I wonder how you did the translation for the other values you have? I assume you don't speak every language in the world, is it all through translation APIs or how do you typically do it?

**Comment by tinohager** [comment]
There are countless projects on github in other languages that I used as a data source. After that I built a simple parser that wrote the values correctly into my classes. And then of course there was some manual work.

**Comment by tinohager** [comment]
e.g. https://github.com/hotosm/iso-countries-languages

**Comment by sthewissen** [comment]
What would be your preferred way of implementing this? I was thinking something along the lines of:

```
public class ItalianInfo : ILanguageInfo
{
    public string CommonName => "Italian";
    public string OfficialName => "Italiano";

    public Translation[] Translations => new[]
    {
        new Translation(LanguageCode.DE, "Italienisch"),
        new Translation(LanguageCode.NL, "Italiaans"),
        new Translation(LanguageCode.EN, "Italian")
        ...
    };

    public LanguageCode LanguageCode => LanguageCode.IT;
}
```

Along with some helper methods to get language names in different languages etc. which would go into a `LanguageProvider` class. Since language and country can be a many-to-many relationship it seems a bit strange to include this in the existing `CountryInfo` logic.

**Comment by tinohager** [comment]
@sthewissen I am currently working on spinning off the translations into a separate project. I would like to see that the basic module remains as small as possible. With all translations we have almost reached a size of 1MB.

**Comment by tinohager** [comment]
@sthewissen The new packages are available on nuget.
