### ISSUE TITLE
Please remove UK/GB from Europe region

### ISSUE THREAD

**Issue by revatim** [nager/Nager.Country#21]
As of 2021, UK has has left EU 
Refer to this - https://www.dfat.gov.au/geo/united-kingdom/brexit
and https://en.wikipedia.org/wiki/Brexit

**Comment by tinohager** [comment]
Okay the move away from europe? 😄 

![image](https://user-images.githubusercontent.com/8215186/221165522-a7816e98-284a-438f-beb7-99ac22791b39.png)
