### ISSUE TITLE
AN - Netherlands Antilles is missing

### ISSUE THREAD

**Issue by racsus** [nager/Nager.Country#24]
I can't find [AN - Netherlands Antilles](https://www.iso.org/obp/ui/#iso:code:3166:AN)

**Comment by tinohager** [comment]
[duplicate issue 13](https://github.com/nager/Nager.Country/issues/13)


The Antilles were [dissolved](https://en.wikipedia.org/wiki/Dissolution_of_the_Netherlands_Antilles) in 2010
