### ISSUE TITLE
Add Italian translation to SaintHelenaCountryTranslation

### ISSUE THREAD

**Issue by Ghevi** [nager/Nager.Country#7]
### Which translation is affected?
SaintHelenaCountryTranslation.

### Description
Add IT translation for this Country. It is missing in file SaintHelenaCountryTranslation.cs
File: https://github.com/nager/Nager.Country/blob/master/src/Nager.Country.Translation/CountryTranslations/SaintHelenaCountryTranslation.cs

**Comment by tinohager** [comment]
And what is the correct translation?
