### ISSUE TITLE
LanguageTranslations are obviously wrong

### ISSUE THREAD

**Issue by marmiskeje** [nager/Nager.Country#8]
Hi.
LanguageTranslations are obsiously wong, e.g. SlovakLanguageTranslation for sk should be "slovenčina" and not "SlovenskejL. What is your source? Can you fix it?

It looks like most of language translations are wrong.

Thanks.

**Comment by samtrion** [comment]
Thank you very much for the hint. We are very grateful for any support from any pull requests.

**Comment by tinohager** [comment]
@marmiskeje The language translations are from a PR https://github.com/nager/Nager.Country/pull/3/files
